# Generated by Django 4.2 on 2023-11-22 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.TextField()),
                ('status', models.CharField(default='Pending')),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2023, 11, 29, 12, 22, 19, 567197, tzinfo=datetime.timezone.utc))),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comapny_invitation', to='api.company')),
            ],
        ),
    ]
