# Generated by Django 4.2 on 2023-11-23 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_position', to='api.companyemployeeposition'),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 12, 50, 20, 385524, tzinfo=datetime.timezone.utc)),
        ),
    ]
