# Generated by Django 4.2 on 2023-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customoutstandingtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
