# Generated by Django 4.2 on 2023-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_permission_userpermission_companyemployee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='group',
            field=models.ManyToManyField(blank=True, to='api.announcementgroup'),
        ),
        migrations.AlterField(
            model_name='announcementgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcementgroup',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='api.useraccount'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='position',
            field=models.CharField(default='Staff'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='role',
            field=models.CharField(default='Staff'),
        ),
    ]
