# Generated by Django 4.2 on 2023-05-05 02:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_announcement_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('position', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='header_create_by', to='api.useraccount')),
                ('header_hide_self', models.ManyToManyField(blank=True, to='api.useraccount')),
                ('hide_by_owner', models.ManyToManyField(blank=True, related_name='header_hide_owner', to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('status', models.CharField(default='Pending')),
                ('progress', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('position', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ManyToManyField(blank=True, related_name='item_assign_to', to='api.useraccount')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_create_by', to='api.useraccount')),
                ('hide_by_owner', models.ManyToManyField(blank=True, related_name='item_hide_owner', to='api.useraccount')),
                ('hide_by_self', models.ManyToManyField(blank=True, related_name='item_hide_self', to='api.useraccount')),
                ('task_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskheader')),
            ],
        ),
    ]
