# Generated by Django 4.2 on 2023-05-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taskheader_taskitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementgroup',
            old_name='companyId',
            new_name='company_id',
        ),
    ]
