# Generated by Django 4.2 on 2023-05-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('accepted', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Reject', 'Reject')])),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('accept_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('promote_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_position', models.CharField(blank=True, null=True)),
                ('new_position', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('promote_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField()),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('address', models.TextField()),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('close', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='hide_by_owner',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='hide_by_self',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='task_header_id',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='salary',
        ),
        migrations.AddField(
            model_name='checkin',
            name='type',
            field=models.CharField(default='Check In'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='language',
            field=models.TextField(default='Chinese'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='prefer_work',
            field=models.TextField(default='High Salary'),
        ),
        migrations.DeleteModel(
            name='TaskHeader',
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='performance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feeback', to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userresume'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
    ]
