# Generated by Django 4.2 on 2023-05-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_companyannouncement_companyannouncementgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='companyEmployeePosition_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.companyemployeeposition'),
            preserve_default=False,
        ),
    ]
