# Generated by Django 4.2 on 2023-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_companyemployee_companyemployeeposition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
