# Generated by Django 4.2 on 2023-05-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_companyemployee_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydepartment',
            old_name='department',
            new_name='department_name',
        ),
    ]
