# Generated by Django 4.2 on 2023-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_department_companydepartment_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybenefits',
            old_name='name',
            new_name='benefit_name',
        ),
        migrations.AddField(
            model_name='companybenefits',
            name='benefit_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
