# Generated by Django 4.2 on 2023-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_companyemployeeevaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployeeevaluate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
