# Generated by Django 4.2 on 2023-06-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_companyemployeeevaluate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployeeLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Personal Leave', 'Personal Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave')])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Cancel', 'Cancel')])),
                ('leave_start', models.DateTimeField()),
                ('leave_end', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('apply_at', models.DateTimeField(auto_now_add=True)),
                ('approve_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('companyEmployee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyemployee')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
