# Generated by Django 4.2 on 2023-07-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userresume_title_alter_userapplicationrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='employeeCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default=''),
        ),
        migrations.CreateModel(
            name='companyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comapny_images', to='api.company')),
            ],
        ),
    ]
