# Generated by Django 4.2 on 2023-07-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_company_contact_company_employeecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='type',
            field=models.CharField(default='Employee'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='employeeCount',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='-', null=True),
        ),
    ]
