# Generated by Django 4.2 on 2023-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_useraccount_type_alter_company_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
