# Generated by Django 4.2 on 2023-10-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gradientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField()),
                ('type', models.CharField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='experience',
        ),
        migrations.AlterField(
            model_name='userresume',
            name='language',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='prefer_work',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('position', models.CharField()),
                ('job_nature', models.CharField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('still_employed', models.BooleanField()),
                ('working_desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField()),
                ('department_name', models.CharField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('educational_qualifications', models.CharField(choices=[('PhD', 'PhD'), ('Master', 'Master'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('High School', 'High School'), ('Higher vocational education', 'Higher vocational education'), ('Junior high school (inclusive) and below', 'Junior high school (inclusive) and below')], default='Degree')),
                ('school_status', models.CharField(choices=[('graduated', 'graduated'), ('studying', 'studying'), ('drop out of school', 'drop out of school')], default='graduated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='userresume',
            name='education',
            field=models.ManyToManyField(blank=True, to='api.education'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience',
            field=models.ManyToManyField(blank=True, to='api.workingexperience'),
        ),
    ]
