# Generated by Django 4.2 on 2023-10-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_recommendoptions_companyemployee_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='edu_user',
        ),
        migrations.RenameField(
            model_name='workingexperience',
            old_name='company_name',
            new_name='we_company_name',
        ),
        migrations.RenameField(
            model_name='workingexperience',
            old_name='user',
            new_name='we_user',
        ),
    ]
