# Generated by Django 4.2 on 2023-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_user_education_edu_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='ur_edu', to='api.education'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='ur_we', to='api.workingexperience'),
        ),
    ]
