# Generated by Django 4.2 on 2023-10-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userresume_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='experience',
        ),
        migrations.AddField(
            model_name='userresume',
            name='education',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ur_edu', to='api.education'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ur_we', to='api.workingexperience'),
        ),
    ]
