# Generated by Django 4.2 on 2023-10-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_userresume_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('goals', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planning', '策劃中'), ('In Progress', '進行中'), ('Completed', '已完成')], default='Planning', max_length=50)),
                ('priority', models.CharField(choices=[('Low', '低'), ('Medium', '中'), ('High', '高'), ('Emergency', '緊急')], default='Medium', max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', '待處理'), ('In Progress', '進行中'), ('Completed', '已完成')], max_length=50)),
                ('due_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraccount')),
                ('task_force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskforce')),
            ],
        ),
    ]
